# Generated by Django 3.1.1 on 2020-09-23 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='Modificado',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Modificado',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='Modificado',
            new_name='modificado',
        ),
    ]
